$(function () {
    // 定义的数据
    var allData_4 = [
        {
            "Organization": "University of Tübingen",
            "Country" : "/style/cvpr2023/img/country/DEU.svg",
            "Rank": 1,
            "team": "CS_Tu",
            "Score": 0.9,
            "ch1_overall_score": 0.83,
            "ch1_avg_displacement_error_within_bound": 0.82,
            "ch1_final_displacement_error_within_bound": 0.6,
            "ch1_miss_rate_within_bound": 0.96,
            "ch1_avg_heading_error_within_bound": 0.94,
            "ch1_final_heading_error_within_bound": 0.92,
            "ch2_overall_score": 0.93,
            "ch2_ego_is_making_progress": 0.99,
            "ch2_drivable_area_compliance": 1,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 0.92,
            "ch2_no_ego_at_fault_collisions": 0.99,
            "ch2_time_to_collision_within_bound": 0.93,
            "ch2_ego_progress_along_expert_route": 0.91,
            "ch2_speed_limit_compliance": 1,
            "ch3_overall_score": 0.93,
            "ch3_ego_is_making_progress": 0.99,
            "ch3_drivable_area_compliance": 1,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 0.93,
            "ch3_no_ego_at_fault_collisions": 0.99,
            "ch3_time_to_collision_within_bound": 0.95,
            "ch3_ego_progress_along_expert_route": 0.88,
            "ch3_speed_limit_compliance": 1
        },
        {
            "Organization": "Horizon Robotics<br>地平线",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 2,
            "team": "autoHorizon2023 (hoplan)",
            "Score": 0.87,
            "ch1_overall_score": 0.85,
            "ch1_avg_displacement_error_within_bound": 0.84,
            "ch1_final_displacement_error_within_bound": 0.66,
            "ch1_miss_rate_within_bound": 0.96,
            "ch1_avg_heading_error_within_bound": 0.96,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.89,
            "ch2_ego_is_making_progress": 0.98,
            "ch2_drivable_area_compliance": 0.99,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.96,
            "ch2_time_to_collision_within_bound": 0.91,
            "ch2_ego_progress_along_expert_route": 0.92,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.88,
            "ch3_ego_is_making_progress": 0.98,
            "ch3_drivable_area_compliance": 0.99,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.96,
            "ch3_time_to_collision_within_bound": 0.92,
            "ch3_ego_progress_along_expert_route": 0.88,
            "ch3_speed_limit_compliance": 0.96
        },
        {
            "Organization": "Pegasus<br>云骥智行",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 3,
            "team": "pegasus_weitao (pegasus_multi_path)",
            "Score": 0.85,
            "ch1_overall_score": 0.88,
            "ch1_avg_displacement_error_within_bound": 0.84,
            "ch1_final_displacement_error_within_bound": 0.73,
            "ch1_miss_rate_within_bound": 0.96,
            "ch1_avg_heading_error_within_bound": 0.95,
            "ch1_final_heading_error_within_bound": 0.93,
            "ch2_overall_score": 0.82,
            "ch2_ego_is_making_progress": 0.93,
            "ch2_drivable_area_compliance": 0.95,
            "ch2_driving_direction_compliance": 0.95,
            "ch2_ego_is_comfortable": 0.93,
            "ch2_no_ego_at_fault_collisions": 0.93,
            "ch2_time_to_collision_within_bound": 0.88,
            "ch2_ego_progress_along_expert_route": 0.79,
            "ch2_speed_limit_compliance": 0.93,
            "ch3_overall_score": 0.85,
            "ch3_ego_is_making_progress": 0.95,
            "ch3_drivable_area_compliance": 0.95,
            "ch3_driving_direction_compliance": 0.96,
            "ch3_ego_is_comfortable": 0.95,
            "ch3_no_ego_at_fault_collisions": 0.95,
            "ch3_time_to_collision_within_bound": 0.91,
            "ch3_ego_progress_along_expert_route": 0.8,
            "ch3_speed_limit_compliance": 0.94
        },
        {
            "Organization": "Nanyang Technological University<br>南洋理工大学",
            "Country" : "/style/cvpr2023/img/country/SGP.svg",
            "Rank": 4,
            "team": "AID (GameFormer Planner)",
            "Score": 0.83,
            "ch1_overall_score": 0.84,
            "ch1_avg_displacement_error_within_bound": 0.81,
            "ch1_final_displacement_error_within_bound": 0.64,
            "ch1_miss_rate_within_bound": 0.97,
            "ch1_avg_heading_error_within_bound": 0.94,
            "ch1_final_heading_error_within_bound": 0.93,
            "ch2_overall_score": 0.81,
            "ch2_ego_is_making_progress": 0.94,
            "ch2_drivable_area_compliance": 0.96,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.94,
            "ch2_no_ego_at_fault_collisions": 0.94,
            "ch2_time_to_collision_within_bound": 0.88,
            "ch2_ego_progress_along_expert_route": 0.84,
            "ch2_speed_limit_compliance": 0.97,
            "ch3_overall_score": 0.84,
            "ch3_ego_is_making_progress": 0.95,
            "ch3_drivable_area_compliance": 0.97,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 0.97,
            "ch3_no_ego_at_fault_collisions": 0.97,
            "ch3_time_to_collision_within_bound": 0.92,
            "ch3_ego_progress_along_expert_route": 0.83,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "Xi'an Jiaotong University<br>西安交通大学",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 5,
            "team": "wheeljack",
            "Score": 0.82,
            "ch1_overall_score": 0.83,
            "ch1_avg_displacement_error_within_bound": 0.81,
            "ch1_final_displacement_error_within_bound": 0.65,
            "ch1_miss_rate_within_bound": 0.95,
            "ch1_avg_heading_error_within_bound": 0.93,
            "ch1_final_heading_error_within_bound": 0.9,
            "ch2_overall_score": 0.81,
            "ch2_ego_is_making_progress": 0.96,
            "ch2_drivable_area_compliance": 0.95,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.82,
            "ch2_no_ego_at_fault_collisions": 0.94,
            "ch2_time_to_collision_within_bound": 0.89,
            "ch2_ego_progress_along_expert_route": 0.82,
            "ch2_speed_limit_compliance": 0.98,
            "ch3_overall_score": 0.82,
            "ch3_ego_is_making_progress": 0.97,
            "ch3_drivable_area_compliance": 0.95,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.85,
            "ch3_no_ego_at_fault_collisions": 0.94,
            "ch3_time_to_collision_within_bound": 0.91,
            "ch3_ego_progress_along_expert_route": 0.84,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 6,
            "team": "xg_test (ltp-planner)",
            "Score": 0.82,
            "ch1_overall_score": 0.88,
            "ch1_avg_displacement_error_within_bound": 0.85,
            "ch1_final_displacement_error_within_bound": 0.7,
            "ch1_miss_rate_within_bound": 0.98,
            "ch1_avg_heading_error_within_bound": 0.97,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.79,
            "ch2_ego_is_making_progress": 0.97,
            "ch2_drivable_area_compliance": 0.97,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 1,
            "ch2_no_ego_at_fault_collisions": 0.88,
            "ch2_time_to_collision_within_bound": 0.82,
            "ch2_ego_progress_along_expert_route": 0.87,
            "ch2_speed_limit_compliance": 0.97,
            "ch3_overall_score": 0.8,
            "ch3_ego_is_making_progress": 0.97,
            "ch3_drivable_area_compliance": 0.98,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 1,
            "ch3_no_ego_at_fault_collisions": 0.9,
            "ch3_time_to_collision_within_bound": 0.86,
            "ch3_ego_progress_along_expert_route": 0.82,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 7,
            "team": "Forecast_MAE (planning, preliminary)",
            "Score": 0.8,
            "ch1_overall_score": 0.91,
            "ch1_avg_displacement_error_within_bound": 0.89,
            "ch1_final_displacement_error_within_bound": 0.76,
            "ch1_miss_rate_within_bound": 0.99,
            "ch1_avg_heading_error_within_bound": 0.97,
            "ch1_final_heading_error_within_bound": 0.95,
            "ch2_overall_score": 0.76,
            "ch2_ego_is_making_progress": 0.98,
            "ch2_drivable_area_compliance": 0.92,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.89,
            "ch2_time_to_collision_within_bound": 0.84,
            "ch2_ego_progress_along_expert_route": 0.84,
            "ch2_speed_limit_compliance": 0.98,
            "ch3_overall_score": 0.73,
            "ch3_ego_is_making_progress": 0.91,
            "ch3_drivable_area_compliance": 0.92,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.94,
            "ch3_time_to_collision_within_bound": 0.9,
            "ch3_ego_progress_along_expert_route": 0.76,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "Motional",
            "Country" : "/style/cvpr2023/img/country/USA.svg",
            "Rank": 8,
            "team": "Host_68305_Team (UrbanDriver)",
            "Score": 0.75,
            "ch1_overall_score": 0.86,
            "ch1_avg_displacement_error_within_bound": 0.83,
            "ch1_final_displacement_error_within_bound": 0.66,
            "ch1_miss_rate_within_bound": 0.97,
            "ch1_avg_heading_error_within_bound": 0.97,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.68,
            "ch2_ego_is_making_progress": 0.95,
            "ch2_drivable_area_compliance": 0.93,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.84,
            "ch2_time_to_collision_within_bound": 0.78,
            "ch2_ego_progress_along_expert_route": 0.84,
            "ch2_speed_limit_compliance": 0.97,
            "ch3_overall_score": 0.7,
            "ch3_ego_is_making_progress": 0.93,
            "ch3_drivable_area_compliance": 0.94,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.88,
            "ch3_time_to_collision_within_bound": 0.84,
            "ch3_ego_progress_along_expert_route": 0.75,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization":
                "The Hong Kong University of Science and Technology (Guangzhou)<br>香港科技大学（广州）",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 9,
            "team": "HatOff2JuiceWRLD (& Haaland)",
            "Score": 0.74,
            "ch1_overall_score": 0.82,
            "ch1_avg_displacement_error_within_bound": 0.79,
            "ch1_final_displacement_error_within_bound": 0.59,
            "ch1_miss_rate_within_bound": 0.93,
            "ch1_avg_heading_error_within_bound": 0.96,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.67,
            "ch2_ego_is_making_progress": 0.94,
            "ch2_drivable_area_compliance": 0.95,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.8,
            "ch2_time_to_collision_within_bound": 0.76,
            "ch2_ego_progress_along_expert_route": 0.83,
            "ch2_speed_limit_compliance": 0.95,
            "ch3_overall_score": 0.75,
            "ch3_ego_is_making_progress": 0.96,
            "ch3_drivable_area_compliance": 0.96,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.88,
            "ch3_time_to_collision_within_bound": 0.85,
            "ch3_ego_progress_along_expert_route": 0.79,
            "ch3_speed_limit_compliance": 0.97
        },
        {
            "Organization": "Mines Paris",
            "Country" : "/style/cvpr2023/img/country/FRA.svg",
            "Rank": 10,
            "team": "raphamas (MBAPPE)",
            "Score": 0.74,
            "ch1_overall_score": 0.79,
            "ch1_avg_displacement_error_within_bound": 0.75,
            "ch1_final_displacement_error_within_bound": 0.57,
            "ch1_miss_rate_within_bound": 0.91,
            "ch1_avg_heading_error_within_bound": 0.91,
            "ch1_final_heading_error_within_bound": 0.9,
            "ch2_overall_score": 0.7,
            "ch2_ego_is_making_progress": 0.95,
            "ch2_drivable_area_compliance": 0.89,
            "ch2_driving_direction_compliance": 0.95,
            "ch2_ego_is_comfortable": 0.91,
            "ch2_no_ego_at_fault_collisions": 0.83,
            "ch2_time_to_collision_within_bound": 0.78,
            "ch2_ego_progress_along_expert_route": 0.79,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.74,
            "ch3_ego_is_making_progress": 0.97,
            "ch3_drivable_area_compliance": 0.9,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.93,
            "ch3_no_ego_at_fault_collisions": 0.86,
            "ch3_time_to_collision_within_bound": 0.82,
            "ch3_ego_progress_along_expert_route": 0.79,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "Tsinghua University<br>清华大学",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 11,
            "team": "LBYD-base",
            "Score": 0.74,
            "ch1_overall_score": 0.89,
            "ch1_avg_displacement_error_within_bound": 0.87,
            "ch1_final_displacement_error_within_bound": 0.72,
            "ch1_miss_rate_within_bound": 0.98,
            "ch1_avg_heading_error_within_bound": 0.96,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.65,
            "ch2_ego_is_making_progress": 0.91,
            "ch2_drivable_area_compliance": 0.89,
            "ch2_driving_direction_compliance": 0.98,
            "ch2_ego_is_comfortable": 0.96,
            "ch2_no_ego_at_fault_collisions": 0.85,
            "ch2_time_to_collision_within_bound": 0.79,
            "ch2_ego_progress_along_expert_route": 0.8,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.67,
            "ch3_ego_is_making_progress": 0.92,
            "ch3_drivable_area_compliance": 0.91,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.98,
            "ch3_no_ego_at_fault_collisions": 0.88,
            "ch3_time_to_collision_within_bound": 0.84,
            "ch3_ego_progress_along_expert_route": 0.78,
            "ch3_speed_limit_compliance": 0.97
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 12,
            "team": "Jit_Ray_Chowdhury",
            "Score": 0.74,
            "ch1_overall_score": 0.83,
            "ch1_avg_displacement_error_within_bound": 0.8,
            "ch1_final_displacement_error_within_bound": 0.61,
            "ch1_miss_rate_within_bound": 0.95,
            "ch1_avg_heading_error_within_bound": 0.96,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.66,
            "ch2_ego_is_making_progress": 0.92,
            "ch2_drivable_area_compliance": 0.91,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.87,
            "ch2_time_to_collision_within_bound": 0.81,
            "ch2_ego_progress_along_expert_route": 0.77,
            "ch2_speed_limit_compliance": 0.97,
            "ch3_overall_score": 0.71,
            "ch3_ego_is_making_progress": 0.95,
            "ch3_drivable_area_compliance": 0.93,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 1,
            "ch3_no_ego_at_fault_collisions": 0.88,
            "ch3_time_to_collision_within_bound": 0.84,
            "ch3_ego_progress_along_expert_route": 0.74,
            "ch3_speed_limit_compliance": 0.97
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 13,
            "team": "Join_planner",
            "Score": 0.71,
            "ch1_overall_score": 0.85,
            "ch1_avg_displacement_error_within_bound": 0.82,
            "ch1_final_displacement_error_within_bound": 0.66,
            "ch1_miss_rate_within_bound": 0.96,
            "ch1_avg_heading_error_within_bound": 0.95,
            "ch1_final_heading_error_within_bound": 0.93,
            "ch2_overall_score": 0.62,
            "ch2_ego_is_making_progress": 0.98,
            "ch2_drivable_area_compliance": 0.83,
            "ch2_driving_direction_compliance": 0.98,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.77,
            "ch2_time_to_collision_within_bound": 0.7,
            "ch2_ego_progress_along_expert_route": 0.89,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.65,
            "ch3_ego_is_making_progress": 0.97,
            "ch3_drivable_area_compliance": 0.83,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.81,
            "ch3_time_to_collision_within_bound": 0.75,
            "ch3_ego_progress_along_expert_route": 0.85,
            "ch3_speed_limit_compliance": 0.97
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 14,
            "team": "Captain",
            "Score": 0.7,
            "ch1_overall_score": 0.75,
            "ch1_avg_displacement_error_within_bound": 0.72,
            "ch1_final_displacement_error_within_bound": 0.58,
            "ch1_miss_rate_within_bound": 0.88,
            "ch1_avg_heading_error_within_bound": 0.87,
            "ch1_final_heading_error_within_bound": 0.86,
            "ch2_overall_score": 0.67,
            "ch2_ego_is_making_progress": 0.88,
            "ch2_drivable_area_compliance": 0.87,
            "ch2_driving_direction_compliance": 0.95,
            "ch2_ego_is_comfortable": 0.84,
            "ch2_no_ego_at_fault_collisions": 0.85,
            "ch2_time_to_collision_within_bound": 0.81,
            "ch2_ego_progress_along_expert_route": 0.65,
            "ch2_speed_limit_compliance": 0.94,
            "ch3_overall_score": 0.67,
            "ch3_ego_is_making_progress": 0.87,
            "ch3_drivable_area_compliance": 0.89,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.85,
            "ch3_no_ego_at_fault_collisions": 0.89,
            "ch3_time_to_collision_within_bound": 0.85,
            "ch3_ego_progress_along_expert_route": 0.61,
            "ch3_speed_limit_compliance": 0.96
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 15,
            "team": "captain_net",
            "Score": 0.69,
            "ch1_overall_score": 0.88,
            "ch1_avg_displacement_error_within_bound": 0.85,
            "ch1_final_displacement_error_within_bound": 0.68,
            "ch1_miss_rate_within_bound": 0.99,
            "ch1_avg_heading_error_within_bound": 0.95,
            "ch1_final_heading_error_within_bound": 0.94,
            "ch2_overall_score": 0.57,
            "ch2_ego_is_making_progress": 0.82,
            "ch2_drivable_area_compliance": 0.94,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 1,
            "ch2_no_ego_at_fault_collisions": 0.88,
            "ch2_time_to_collision_within_bound": 0.84,
            "ch2_ego_progress_along_expert_route": 0.48,
            "ch2_speed_limit_compliance": 0.99,
            "ch3_overall_score": 0.61,
            "ch3_ego_is_making_progress": 0.83,
            "ch3_drivable_area_compliance": 0.94,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 1,
            "ch3_no_ego_at_fault_collisions": 0.92,
            "ch3_time_to_collision_within_bound": 0.9,
            "ch3_ego_progress_along_expert_route": 0.5,
            "ch3_speed_limit_compliance": 0.99
        },
        {
            "Organization": "C&BIS",
            "Country" : "/style/cvpr2023/img/country/KOR.svg",
            "Rank": 16,
            "team": "adet",
            "Score": 0.66,
            "ch1_overall_score": 0.72,
            "ch1_avg_displacement_error_within_bound": 0.71,
            "ch1_final_displacement_error_within_bound": 0.47,
            "ch1_miss_rate_within_bound": 0.87,
            "ch1_avg_heading_error_within_bound": 0.95,
            "ch1_final_heading_error_within_bound": 0.92,
            "ch2_overall_score": 0.6,
            "ch2_ego_is_making_progress": 0.91,
            "ch2_drivable_area_compliance": 0.96,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.8,
            "ch2_no_ego_at_fault_collisions": 0.81,
            "ch2_time_to_collision_within_bound": 0.76,
            "ch2_ego_progress_along_expert_route": 0.64,
            "ch2_speed_limit_compliance": 1,
            "ch3_overall_score": 0.65,
            "ch3_ego_is_making_progress": 0.92,
            "ch3_drivable_area_compliance": 0.95,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.81,
            "ch3_no_ego_at_fault_collisions": 0.87,
            "ch3_time_to_collision_within_bound": 0.83,
            "ch3_ego_progress_along_expert_route": 0.65,
            "ch3_speed_limit_compliance": 0.99
        },
        {
            "Organization": "C&BIS",
            "Country" : "/style/cvpr2023/img/country/KOR.svg",
            "Rank": 17,
            "team": "bbbong",
            "Score": 0.64,
            "ch1_overall_score": 0.71,
            "ch1_avg_displacement_error_within_bound": 0.69,
            "ch1_final_displacement_error_within_bound": 0.44,
            "ch1_miss_rate_within_bound": 0.85,
            "ch1_avg_heading_error_within_bound": 0.95,
            "ch1_final_heading_error_within_bound": 0.92,
            "ch2_overall_score": 0.61,
            "ch2_ego_is_making_progress": 0.83,
            "ch2_drivable_area_compliance": 0.96,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 0.91,
            "ch2_no_ego_at_fault_collisions": 0.89,
            "ch2_time_to_collision_within_bound": 0.85,
            "ch2_ego_progress_along_expert_route": 0.52,
            "ch2_speed_limit_compliance": 1,
            "ch3_overall_score": 0.6,
            "ch3_ego_is_making_progress": 0.82,
            "ch3_drivable_area_compliance": 0.96,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 0.89,
            "ch3_no_ego_at_fault_collisions": 0.9,
            "ch3_time_to_collision_within_bound": 0.87,
            "ch3_ego_progress_along_expert_route": 0.51,
            "ch3_speed_limit_compliance": 1
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 18,
            "team": "avr",
            "Score": 0.63,
            "ch1_overall_score": 0.25,
            "ch1_avg_displacement_error_within_bound": 0.38,
            "ch1_final_displacement_error_within_bound": 0.12,
            "ch1_miss_rate_within_bound": 0.32,
            "ch1_avg_heading_error_within_bound": 0.91,
            "ch1_final_heading_error_within_bound": 0.86,
            "ch2_overall_score": 0.81,
            "ch2_ego_is_making_progress": 0.91,
            "ch2_drivable_area_compliance": 0.99,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 0.84,
            "ch2_no_ego_at_fault_collisions": 0.97,
            "ch2_time_to_collision_within_bound": 0.9,
            "ch2_ego_progress_along_expert_route": 0.83,
            "ch2_speed_limit_compliance": 1,
            "ch3_overall_score": 0.83,
            "ch3_ego_is_making_progress": 0.92,
            "ch3_drivable_area_compliance": 0.99,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 0.88,
            "ch3_no_ego_at_fault_collisions": 0.98,
            "ch3_time_to_collision_within_bound": 0.95,
            "ch3_ego_progress_along_expert_route": 0.81,
            "ch3_speed_limit_compliance": 1
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 19,
            "team": "Driver_go",
            "Score": 0.61,
            "ch1_overall_score": 0.68,
            "ch1_avg_displacement_error_within_bound": 0.68,
            "ch1_final_displacement_error_within_bound": 0.44,
            "ch1_miss_rate_within_bound": 0.82,
            "ch1_avg_heading_error_within_bound": 0.94,
            "ch1_final_heading_error_within_bound": 0.9,
            "ch2_overall_score": 0.56,
            "ch2_ego_is_making_progress": 0.91,
            "ch2_drivable_area_compliance": 0.83,
            "ch2_driving_direction_compliance": 0.96,
            "ch2_ego_is_comfortable": 0.97,
            "ch2_no_ego_at_fault_collisions": 0.79,
            "ch2_time_to_collision_within_bound": 0.75,
            "ch2_ego_progress_along_expert_route": 0.68,
            "ch2_speed_limit_compliance": 0.99,
            "ch3_overall_score": 0.59,
            "ch3_ego_is_making_progress": 0.9,
            "ch3_drivable_area_compliance": 0.85,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.97,
            "ch3_no_ego_at_fault_collisions": 0.83,
            "ch3_time_to_collision_within_bound": 0.8,
            "ch3_ego_progress_along_expert_route": 0.66,
            "ch3_speed_limit_compliance": 0.99
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 20,
            "team": "crazy_planner",
            "Score": 0.6,
            "ch1_overall_score": 0.77,
            "ch1_avg_displacement_error_within_bound": 0.78,
            "ch1_final_displacement_error_within_bound": 0.56,
            "ch1_miss_rate_within_bound": 0.89,
            "ch1_avg_heading_error_within_bound": 0.92,
            "ch1_final_heading_error_within_bound": 0.89,
            "ch2_overall_score": 0.52,
            "ch2_ego_is_making_progress": 0.83,
            "ch2_drivable_area_compliance": 0.86,
            "ch2_driving_direction_compliance": 0.95,
            "ch2_ego_is_comfortable": 0.94,
            "ch2_no_ego_at_fault_collisions": 0.73,
            "ch2_time_to_collision_within_bound": 0.69,
            "ch2_ego_progress_along_expert_route": 0.7,
            "ch2_speed_limit_compliance": 0.94,
            "ch3_overall_score": 0.52,
            "ch3_ego_is_making_progress": 0.82,
            "ch3_drivable_area_compliance": 0.86,
            "ch3_driving_direction_compliance": 0.96,
            "ch3_ego_is_comfortable": 0.96,
            "ch3_no_ego_at_fault_collisions": 0.78,
            "ch3_time_to_collision_within_bound": 0.75,
            "ch3_ego_progress_along_expert_route": 0.68,
            "ch3_speed_limit_compliance": 0.95
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 21,
            "team": "Host_68305_Team (IDMPlanner)",
            "Score": 0.59,
            "ch1_overall_score": 0.29,
            "ch1_avg_displacement_error_within_bound": 0.43,
            "ch1_final_displacement_error_within_bound": 0.19,
            "ch1_miss_rate_within_bound": 0.36,
            "ch1_avg_heading_error_within_bound": 0.9,
            "ch1_final_heading_error_within_bound": 0.87,
            "ch2_overall_score": 0.72,
            "ch2_ego_is_making_progress": 0.94,
            "ch2_drivable_area_compliance": 0.9,
            "ch2_driving_direction_compliance": 1,
            "ch2_ego_is_comfortable": 0.93,
            "ch2_no_ego_at_fault_collisions": 0.9,
            "ch2_time_to_collision_within_bound": 0.81,
            "ch2_ego_progress_along_expert_route": 0.81,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.75,
            "ch3_ego_is_making_progress": 0.95,
            "ch3_drivable_area_compliance": 0.9,
            "ch3_driving_direction_compliance": 1,
            "ch3_ego_is_comfortable": 0.93,
            "ch3_no_ego_at_fault_collisions": 0.91,
            "ch3_time_to_collision_within_bound": 0.85,
            "ch3_ego_progress_along_expert_route": 0.83,
            "ch3_speed_limit_compliance": 0.96
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 22,
            "team": "changdrive",
            "Score": 0.57,
            "ch1_overall_score": 0.66,
            "ch1_avg_displacement_error_within_bound": 0.68,
            "ch1_final_displacement_error_within_bound": 0.44,
            "ch1_miss_rate_within_bound": 0.8,
            "ch1_avg_heading_error_within_bound": 0.94,
            "ch1_final_heading_error_within_bound": 0.9,
            "ch2_overall_score": 0.52,
            "ch2_ego_is_making_progress": 0.94,
            "ch2_drivable_area_compliance": 0.82,
            "ch2_driving_direction_compliance": 0.97,
            "ch2_ego_is_comfortable": 0.98,
            "ch2_no_ego_at_fault_collisions": 0.73,
            "ch2_time_to_collision_within_bound": 0.69,
            "ch2_ego_progress_along_expert_route": 0.73,
            "ch2_speed_limit_compliance": 0.99,
            "ch3_overall_score": 0.54,
            "ch3_ego_is_making_progress": 0.94,
            "ch3_drivable_area_compliance": 0.8,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.98,
            "ch3_no_ego_at_fault_collisions": 0.77,
            "ch3_time_to_collision_within_bound": 0.72,
            "ch3_ego_progress_along_expert_route": 0.73,
            "ch3_speed_limit_compliance": 0.99
        },
        {
            "Organization": "Intel",
            "Country" : "/style/cvpr2023/img/country/USA.svg",
            "Rank": 23,
            "team": "Lidan",
            "Score": 0.57,
            "ch1_overall_score": 0.64,
            "ch1_avg_displacement_error_within_bound": 0.7,
            "ch1_final_displacement_error_within_bound": 0.46,
            "ch1_miss_rate_within_bound": 0.78,
            "ch1_avg_heading_error_within_bound": 0.88,
            "ch1_final_heading_error_within_bound": 0.81,
            "ch2_overall_score": 0.53,
            "ch2_ego_is_making_progress": 0.76,
            "ch2_drivable_area_compliance": 0.83,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.99,
            "ch2_no_ego_at_fault_collisions": 0.81,
            "ch2_time_to_collision_within_bound": 0.79,
            "ch2_ego_progress_along_expert_route": 0.54,
            "ch2_speed_limit_compliance": 1,
            "ch3_overall_score": 0.55,
            "ch3_ego_is_making_progress": 0.76,
            "ch3_drivable_area_compliance": 0.84,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.99,
            "ch3_no_ego_at_fault_collisions": 0.86,
            "ch3_time_to_collision_within_bound": 0.84,
            "ch3_ego_progress_along_expert_route": 0.52,
            "ch3_speed_limit_compliance": 1
        },
        {
            "Organization": "China Telecommunications Corporation<br>中国电信集团有限公司",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 24,
            "team": "Ctyun",
            "Score": 0.51,
            "ch1_overall_score": 0.48,
            "ch1_avg_displacement_error_within_bound": 0.59,
            "ch1_final_displacement_error_within_bound": 0.34,
            "ch1_miss_rate_within_bound": 0.58,
            "ch1_avg_heading_error_within_bound": 0.92,
            "ch1_final_heading_error_within_bound": 0.87,
            "ch2_overall_score": 0.53,
            "ch2_ego_is_making_progress": 0.83,
            "ch2_drivable_area_compliance": 0.89,
            "ch2_driving_direction_compliance": 0.99,
            "ch2_ego_is_comfortable": 0.97,
            "ch2_no_ego_at_fault_collisions": 0.84,
            "ch2_time_to_collision_within_bound": 0.79,
            "ch2_ego_progress_along_expert_route": 0.58,
            "ch2_speed_limit_compliance": 0.99,
            "ch3_overall_score": 0.53,
            "ch3_ego_is_making_progress": 0.82,
            "ch3_drivable_area_compliance": 0.89,
            "ch3_driving_direction_compliance": 0.99,
            "ch3_ego_is_comfortable": 0.96,
            "ch3_no_ego_at_fault_collisions": 0.85,
            "ch3_time_to_collision_within_bound": 0.82,
            "ch3_ego_progress_along_expert_route": 0.57,
            "ch3_speed_limit_compliance": 0.99
        },
        {
            "Organization": "-",
            "Country" : "/style/cvpr2023/img/country/blank.png",
            "Rank": 25,
            "team": "NaNny (raster_model)",
            "Score": 0.42,
            "ch1_overall_score": 0.38,
            "ch1_avg_displacement_error_within_bound": 0.44,
            "ch1_final_displacement_error_within_bound": 0.21,
            "ch1_miss_rate_within_bound": 0.48,
            "ch1_avg_heading_error_within_bound": 0.91,
            "ch1_final_heading_error_within_bound": 0.86,
            "ch2_overall_score": 0.41,
            "ch2_ego_is_making_progress": 0.92,
            "ch2_drivable_area_compliance": 0.75,
            "ch2_driving_direction_compliance": 0.93,
            "ch2_ego_is_comfortable": 0.76,
            "ch2_no_ego_at_fault_collisions": 0.58,
            "ch2_time_to_collision_within_bound": 0.54,
            "ch2_ego_progress_along_expert_route": 0.79,
            "ch2_speed_limit_compliance": 0.96,
            "ch3_overall_score": 0.45,
            "ch3_ego_is_making_progress": 0.91,
            "ch3_drivable_area_compliance": 0.76,
            "ch3_driving_direction_compliance": 0.95,
            "ch3_ego_is_comfortable": 0.79,
            "ch3_no_ego_at_fault_collisions": 0.65,
            "ch3_time_to_collision_within_bound": 0.59,
            "ch3_ego_progress_along_expert_route": 0.78,
            "ch3_speed_limit_compliance": 0.95
        },
        {
            "Organization": "Motional",
            "Country" : "/style/cvpr2023/img/country/USA.svg",
            "Rank": 26,
            "team": "Host_68305_Team (SimplePlanner)",
            "Score": 0.31,
            "ch1_overall_score": 0.22,
            "ch1_avg_displacement_error_within_bound": 0.38,
            "ch1_final_displacement_error_within_bound": 0.18,
            "ch1_miss_rate_within_bound": 0.26,
            "ch1_avg_heading_error_within_bound": 0.86,
            "ch1_final_heading_error_within_bound": 0.79,
            "ch2_overall_score": 0.32,
            "ch2_ego_is_making_progress": 0.71,
            "ch2_drivable_area_compliance": 0.79,
            "ch2_driving_direction_compliance": 0.97,
            "ch2_ego_is_comfortable": 0.81,
            "ch2_no_ego_at_fault_collisions": 0.69,
            "ch2_time_to_collision_within_bound": 0.67,
            "ch2_ego_progress_along_expert_route": 0.51,
            "ch2_speed_limit_compliance": 0.98,
            "ch3_overall_score": 0.37,
            "ch3_ego_is_making_progress": 0.71,
            "ch3_drivable_area_compliance": 0.79,
            "ch3_driving_direction_compliance": 0.97,
            "ch3_ego_is_comfortable": 0.81,
            "ch3_no_ego_at_fault_collisions": 0.76,
            "ch3_time_to_collision_within_bound": 0.74,
            "ch3_ego_progress_along_expert_route": 0.51,
            "ch3_speed_limit_compliance": 0.98
        },
        {
            "Organization": "University of Science and Technology of China<br>中国科学技术大学",
            "Country" : "/style/cvpr2023/img/country/CHN.svg",
            "Rank": 27,
            "team": "NIC-showtime (LaneGCN)",
            "Score": 0.18,
            "ch1_overall_score": 0.27,
            "ch1_avg_displacement_error_within_bound": null,
            "ch1_final_displacement_error_within_bound": null,
            "ch1_miss_rate_within_bound": null,
            "ch1_avg_heading_error_within_bound": null,
            "ch1_final_heading_error_within_bound": null,
            "ch2_overall_score": 	0.11,
            "ch2_ego_is_making_progress": null,
            "ch2_drivable_area_compliance": null,
            "ch2_driving_direction_compliance": null,
            "ch2_ego_is_comfortable": null,
            "ch2_no_ego_at_fault_collisions": null,
            "ch2_time_to_collision_within_bound": null,
            "ch2_ego_progress_along_expert_route": null,
            "ch2_speed_limit_compliance": null,
            "ch3_overall_score": 0.14,
            "ch3_ego_is_making_progress": null,
            "ch3_drivable_area_compliance": null,
            "ch3_driving_direction_compliance": null,
            "ch3_ego_is_comfortable": null,
            "ch3_no_ego_at_fault_collisions": null,
            "ch3_time_to_collision_within_bound": null,
            "ch3_ego_progress_along_expert_route": null,
            "ch3_speed_limit_compliance": null
        }
    ]
    // 每页显示数据量
    var page_4 = 10
    // 总条目数
    var total_4 = allData_4.length
    // 总页数
    var pages_4 = Math.ceil(total_4 / page_4)
    // 当前页
    var curPage_4 = 1
    renderList(allData_4)
    // 渲染数据列表
    function num(i) {
        var n = i.toFixed(2);
        return(n);
        }
        function filter(i) {
            if(i == '/style/cvpr2023/img/country/blank.png'){
                return('-')
            } else {
                return('<img src='+i+' style="width: 33px; user-select: none;"/>')
            }
        }
    function renderList(data) {
        // 总页数
        pages_4 = Math.ceil(total_4 / page_4)
        $(".table_list_4 tbody tr:not(:last-child)").remove()
        data = data.slice((curPage_4 - 1) * page_4, page_4 * curPage_4)
        // 渲染列表数据
        data.forEach((item, index) => {
            var htmlStr = `<tr class="item">
        <td>${item.Rank}</td>
        <td>${item.team}</td>
        <td>${filter(item.Country)}</td>
        <td>${item.Organization}</td>
        <td><b>${num(item.Score)}</b></td>
        <td>${num(item.ch1_overall_score)}</td>
        <td>${num(item.ch2_overall_score)}</td>
        <td>${num(item.ch3_overall_score)}</td>
      </tr>

      `
            $(htmlStr).insertBefore($(".page_4"))
        })
        // 初始化 分页数据
        $("#curpage_4").val(curPage_4)
        // 总页数渲染
        $("#total_4").text(pages_4)
    }
    // 根据name进行排序
    $(".table_list_4 tr th:nth-child(1)").click(function () {
        mysort($(this), 'Rank', allData_4)
    })
    // $(".table_list_4 tr th:nth-child(2)").click(function () {
    //     mysort($(this), 'team', allData_4)
    // })
    $(".table_list_4 tr th:nth-child(5)").click(function () {
        mysort($(this), 'Score', allData_4)
    })
    $(".table_list_4 tr th:nth-child(6)").click(function () {
        mysort($(this), 'ch1_overall_score', allData_4)
    })
    $(".table_list_4 tr th:nth-child(7)").click(function () {
        mysort($(this), 'ch2_overall_score', allData_4)
    })
    $(".table_list_4 tr th:nth-child(8)").click(function () {
        mysort($(this), 'ch3_overall_score', allData_4)
    })
    // 排序方法
    function mysort(obj, field, data) {
        obj.siblings("th").removeClass()
        if (obj.hasClass("asc") || [undefined, ''].includes(obj.attr("class"))) {
            obj.attr({ "class": "desc" })
            data.sort(function (a, b) {
                if (a[field] > b[field]) {
                    return -1;
                }
            });
        } else if (obj.hasClass("desc")) {
            obj.attr({ "class": "asc" })
            data.sort(function (a, b) {
                if (a[field] < b[field]) {
                    return -1;
                }
            });
        }
        renderList(data)
    }
    // 选择每页显示的数据量
    $("#pageOption_4").change(function () {
        page_4 = $(this).val()
        renderList(allData_4)
    })
    // 上一页
    $("#prev_4").click(function () {
        curPage_4--
        if (curPage_4 <= 0) {
            curPage_4 = 1;
            $(this).prop('disabled', true)
        }
        $("#next_4").prop('disabled', false)
        $("#curPage_4").val(curPage_4)
        renderList(allData_4)
    })
    // 下一页
    $("#next_4").click(function () {
        curPage_4++
        if (curPage_4 >= pages_4) {
            curPage_4 = pages_4;
            $(this).prop('disabled', true)
        }
        $("#prev_4").prop("disabled", false)
        $("#curPage_4").val(curPage_4)
        renderList(allData_4)
    })
    // 手动输入页码
    $("#curpage_4").change(function () {
        var inpVal = $(this).val()
        console.log(inpVal);
        if (inpVal <= 0) {
            curPage_4 = 1
            $("#prev_4").prop("disabled", true);
            $("#next_4").prop("disabled", false);
        } else if (inpVal > pages_4) {
            curPage_4 = pages_4
            $("#next_4").prop("disabled", true);
            $("#prev_4").prop("disabled", false);
        } else {
            $("#next_4").prop("disabled", false);
            $("#prev_4").prop("disabled", false);
            curPage_4 = inpVal
        }
        renderList(allData_4)
    })
})
